#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Training_FW
EXTRA_COMPONENT_DIRS := ./Components
include $(IDF_PATH)/make/project.mk
